package merge

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/nimling/samna-migrate/internal/config"
	"github.com/nimling/samna-migrate/internal/db"
	"github.com/nimling/samna-migrate/internal/dump"
	"github.com/nimling/samna-migrate/internal/log"
	"github.com/nimling/samna-migrate/internal/steps"
)

// Rebase generates .upgraded/ from live database state.
func Rebase(ctx context.Context, d *db.DB, cfg *config.Config, stepsCfg *steps.Config, dbDir, toolVersion string, force bool) error {
	upgradedDir := filepath.Join(filepath.Dir(cfg.StepsFile), ".upgraded")
	if info, err := os.Stat(upgradedDir); err == nil && info.IsDir() {
		if hasContent(upgradedDir) {
			if !force {
				return fmt.Errorf(".upgraded/ already exists with content. Use --force to overwrite")
			}
			os.RemoveAll(upgradedDir)
		}
	}

	pending, err := pendingCount(ctx, d)
	if err != nil {
		return err
	}
	if pending > 0 {
		return fmt.Errorf("%d pending migrations on disk. Run 'smig up' first", pending)
	}

	if err := os.MkdirAll(upgradedDir, 0o755); err != nil {
		return err
	}

	log.Header("pass 1: live SQL into .upgraded/")

	for _, st := range stepsCfg.Steps {
		if st.Type == "migration" {
			continue
		}
		files, err := st.ResolveFiles(dbDir)
		if err != nil {
			return err
		}
		if len(files) == 0 {
			continue
		}
		paths := make([]string, 0, len(files))
		for _, f := range files {
			paths = append(paths, f.AbsPath)
		}
		flags, _ := dump.DetectSourceUses(paths)
		merged, err := dump.ObjectsForSchemas(ctx, d, cfg, st.Schemas, flags)
		if err != nil {
			return fmt.Errorf("dump for step %s: %w", st.Name, err)
		}
		for _, f := range files {
			outDir := filepath.Join(upgradedDir, f.Folder)
			os.MkdirAll(outDir, 0o755)
			outFile := filepath.Join(outDir, f.Name)
			header := fmt.Sprintf("-- step %s\n-- type %s slug %s schemas %s\n-- generated by smig %s at %s\n-- source %s\n\n",
				st.Name, st.Type, st.Slug, strings.Join(st.Schemas, ","), toolVersion, time.Now().UTC().Format(time.RFC3339), f.Rel)
			if err := os.WriteFile(outFile, []byte(header+merged), 0o644); err != nil {
				return err
			}
			log.Success("wrote %s", filepath.Join(f.Folder, f.Name))
		}
	}

	log.Header("pass 2: route migrations")

	registry, err := buildIdentifierRegistry(stepsCfg, dbDir)
	if err != nil {
		return err
	}

	migOut := filepath.Join(upgradedDir, "migrations")
	os.MkdirAll(migOut, 0o755)

	for _, st := range stepsCfg.Steps {
		if st.Type != "migration" {
			continue
		}
		files, err := st.ResolveFiles(dbDir)
		if err != nil {
			return err
		}
		for _, f := range files {
			introduced, _ := introducedIdents(f.AbsPath)
			routed := ""
			for _, id := range introduced {
				if base, ok := registry[id]; ok {
					routed = base
					break
				}
			}
			dest := filepath.Join(migOut, f.Name)
			if routed != "" {
				// folded into a base file; write empty placeholder
				if err := os.WriteFile(dest, []byte{}, 0o644); err != nil {
					return err
				}
				log.Success("  ✓ %s -> %s", f.Name, routed)
			} else {
				if err := copyFile(f.AbsPath, dest); err != nil {
					return err
				}
				log.Warn("  ! %s -> .upgraded/migrations (review)", f.Name)
			}
		}
	}

	log.Success(".upgraded/ ready at %s", upgradedDir)
	log.Info("review the tree, run smig verify, then smig merge --apply")
	return nil
}

func hasContent(p string) bool {
	entries, err := os.ReadDir(p)
	return err == nil && len(entries) > 0
}

func pendingCount(ctx context.Context, d *db.DB) (int, error) {
	var n int
	err := d.Pool.QueryRow(ctx, `SELECT COUNT(*) FROM samna_migrate.file WHERE state = 'pending'`).Scan(&n)
	return n, err
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func buildIdentifierRegistry(stepsCfg *steps.Config, dbDir string) (map[string]string, error) {
	reg := map[string]string{}
	for _, st := range stepsCfg.Steps {
		if st.Type == "migration" {
			continue
		}
		files, err := st.ResolveFiles(dbDir)
		if err != nil {
			return nil, err
		}
		for _, f := range files {
			ids, _ := introducedIdents(f.AbsPath)
			for _, id := range ids {
				if _, ok := reg[id]; !ok {
					reg[id] = filepath.Join(f.Folder, f.Name)
				}
			}
		}
	}
	return reg, nil
}

var rxIntroduced = regexp.MustCompile(`(?i)CREATE\s+(OR\s+REPLACE\s+)?(FUNCTION|PROCEDURE|TABLE|VIEW|TRIGGER|TYPE|INDEX|SEQUENCE)(\s+IF\s+NOT\s+EXISTS)?\s+([a-z_0-9.]+)`)

func introducedIdents(path string) ([]string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	matches := rxIntroduced.FindAllStringSubmatch(string(b), -1)
	out := make([]string, 0, len(matches))
	seen := map[string]bool{}
	for _, m := range matches {
		id := strings.ToLower(m[4])
		if seen[id] {
			continue
		}
		seen[id] = true
		out = append(out, id)
	}
	sort.Strings(out)
	return out, nil
}
